# Site settings
title: vinicius.dacal
jobtitle: Front end Developer
email: viniciusldacal@gmail.com
description: "Tutoriais, artigos e materiais para estudos de desenvolvimento web."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://viniciusdacal.com" # the base hostname & protocol for your site
twitter_username: vinicius_dacal
github_username:  viniciusdacal
facebook:  https://www.facebook.com/viniciusdacal
linkedin: https://www.linkedin.com/in/viniciusdacal
gplus: https://plus.google.com/+viniciusdacallopes
mainKeywords: "frontend, web development, tecnologia web, css, html, javascript, php, python, ruby, java, backend, programming"

# Build settings
markdown: kramdown
sass:
    style: :compressed
#blog layout settings

months:
  Jan: "Janeiro"
  Feb: "Fevereiro"
  Mar: "Março"
  Apr: "Abril"
  May: "Maio"
  Jun: "Junho"
  July: "Julho"
  Aug: "Agosto"
  Sep: "Setembro"
  Oct: "Outubro"
  Nov: "Novembro"
  Dec: "Dezembro"

defaults:
  # Default language
  -
    scope:
      path: ""
    values:
      lang: "pt"
  # Language for everything inside `/en`
  -
    scope:
      path: "en"
    values:
      lang: "en"
  # Language for English posts
  -
    scope:
      path: "en/_posts"
      type: "posts" # As of version 2.3.0, Jekyll uses plural keywords for type
    values:
      lang: "en"


t:
  en:
    home:
      name: "home"
      url: "/en/"
    about:
      name: "about.me"
      url: "/en/about/"
    projects:
      name: "projects"
      url: "/en/projects/"
  pt:
    home:
      name: "home"
      url: "/"
    about:
      name: "about.me"
      url: "/about/"
    projects:
        name: "projetos"
        url: "/projects/"