backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    path: "{{year}}/{{identifier}}/{{language}}"
    slug: "{{year}}/{{identifier}}/{{language}}"
    media_folder: '/content/blog/_imgs'
    public_folder: '/blog/img'
    create: true
    editor:
     preview: false
    fields:
      - {
          label: "Slug em português",
          name: "identifier",
          widget: "string",
          pattern: "([A-Za-z-])",
          hint: "Espaços ou acentos não são permitidos"
        }
      - {
          label: "Idioma",
          name: "language",
          widget: "select",
          default: "pt-br",
          options: [
            { label: "pt-br", value: "pt-br" },
            { label: "EN", value: "en" },
          ]
        }
      - {
          label: "Capa",
          name: "image",
          widget: "image",
          media_library: {
            config: {
              multiple: true
            }
          }
        }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
