backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "/content/blog/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Títutlo", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Descrição", name: "description", widget: "text"}
      - {label: "Idioma", name: "language", widget: "string"}
      - {label: "Imagem", name: "image", widget: image}
      - {label: "Texto", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

